### ISSUE TITLE
Kanban Board Creation

### ISSUE THREAD

**Issue by lenkon** [baqar-abbas/rubyCapstone-catalog-of-things#38]
We are 3 members in our group.
Team member #1 is @baqar-abbas  
Team member #2 is @DilsherB 
Team member #3 is @lenkon 

Here is our project link https://github.com/baqar-abbas/rubyCapstone-catalog-of-things/projects/1

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼, 

![approved](https://github.com/baqar-abbas/rubyCapstone-catalog-of-things/assets/64643995/379ce9e5-2dd0-45cf-a1f4-b30e0969905a)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Points are fairly distributed amongst team members👍🏼.
- [x] A link to the github project has been provided👍🏼.
- [x] Each card has a descriptive title, number of points and task description👍🏼.
- [x] All cards are assigned to a team member👍🏼.
- [x] All requirements has been captured in the various cards👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
